version: 2.1
orbs:
  coveralls: coveralls/coveralls@2.2.1
jobs:
  build:
    docker:
      - image: node:20

    working_directory: ~/repo

    steps:
      - checkout
      # - run:
      #     name: Install libssl1.1
      #     command: |
      #       # wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
      #       # sudo dpkg -i ./libssl1.1_1.1.0g-2ubuntu4_amd64.deb
      #       # sudo apt-get install curl libcurl4
      #       wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc |  gpg --dearmor | sudo tee /usr/share/keyrings/mongodb.gpg > /dev/null
      #       echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
      #       sudo apt update
      #       sudo apt install -y mongodb-org
      #       MONGOMS_SYSTEM_BINARY=/usr/bin/mongosh
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # check npm dependencies for security risks - run 'npm audit' to fix
      - run: npx audit-ci -m --report-type full -w decompress

      # install dependecies
      - run: npm ci

      - save_cache:
          paths:
            - ~/.npm
          key: v1-dependencies-{{ checksum "package.json" }}

      # ensure code style standards are adhered to - run 'npm run style:fix' to fix
      - run: npm run style
      - run: npm run lint

      # - run: npm run standalone

      # run tests and store test results
      - run:
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./test_results/
      - store_test_results:
          path: ./test_results

      # upload coverage report to coveralls for readme badge support
      # requires config.yml version 2.1 and orbs: coveralls: coveralls/coveralls@1.0.4
      # requires coveralls account and token specific to repo to be stored in CircleCI
      - coveralls/upload
      - run: npm pack
      - run:
          command: |
            mkdir -p /tmp/circle-artifacts
            cp *.tgz /tmp/circle-artifacts
      - store_artifacts:
          path: /tmp/circle-artifacts
      - run:
          name: Move compiled app to workspace
          command: |
            set -exu
            mkdir -p /tmp/workspace/pkg
            mv *.tgz /tmp/workspace/pkg/
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - pkg
  deploy:
    docker:
      - image: cimg/node:current
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish $(echo /tmp/workspace/pkg/*.tgz)
workflows:
  build-and-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: main
      - deploy:
          context: npm
          requires:
            - hold
